### ISSUE TITLE
Cant upload to raindrop with API

### ISSUE THREAD

**Issue by Luiggy** [raindropio/developer-site#2]
We are trying to develop a Telegram Bot and integrating your service on it. 
When we test getting the collection by _ID,_ it works perfectly.
But when we try to upload a new link as a raindrop to a collection, or without a collection, the Rest API return an error saying that there are 3 required arguments. 

As it is explained in the [documentation](https://developer.raindrop.io/v1/raindrops/single), the only required parameter is the parameter **'link'** with any string value. but nothing happens.
When we execute the request the response is requesting for more arguments such as '**domain**' and **'title'**, but if we send also those ones, it also returns the same error.

Could you please help us developing this part or telling us the correct arguments we have to send or how to call the API? 

Thanks in advance
![image](https://user-images.githubusercontent.com/1401734/77001346-1647d180-695a-11ea-8157-a35f834e0008.png)

**Comment by exentrich** [comment]
Seems like POST request send JSON payload incorrectly. I don’t know Python but could you try to simulate this request in Postman for example?
‘link’ is only required field, ‘title’ and ‘domain’ will be automatically recognized.

This API is used in all our apps, so I’m pretty sure that it works correctly. I could show example in JavaScript if it helps

**Comment by exentrich** [comment]
Also ‘domain’ should be without protocol, just for example ‘blog.hackingteam.space’

**Comment by exentrich** [comment]
Stackoverflow suggest to use `json` parameter in request `requests.post(‘http://httpbin.org/post’, json={“key”: “value”})`

**Comment by ConnorXploit** [comment]
Hi!

I'm in the same team as @Luiggy and i have changed 'params' to 'json' and is working perfectly!

Thanks!

**Comment by Luiggy** [comment]
Thank you so much ! 
dint realise that ^_^
