### ISSUE TITLE
Limit to 25 bookmarks

### ISSUE THREAD

**Issue by starchildluke** [raindropio/developer-site#4]
You'll have to bear with me as I've never submitted an issue before.

I'm using the following code to generate random bookmark links tagged with the word "black".

```
import requests
import random

headers = {'Authorization': 'Bearer AUTHORISATION CODE'}

raindrop_list = []

r = requests.get('https://api.raindrop.io/rest/v1/raindrops/0?search=[{"key":"tag","val":"black"}]',
					headers=headers)

response = r.json()

items = response["items"]

for num in range(len(items)):
	title = items[num]["title"]
	link = items[num]["link"]
	title_link = (title, link)		
	raindrop_list.append(title_link)

rand = random.randint(0,len(raindrop_list)-1)

print(raindrop_list)
```

But it only iterates through a maximum of 25 bookmarks and there are more than 25 bookmarks tagged with the word "black". Is that a bug or a feature?

**Comment by exentrich** [comment]
Thats default limit per page. You can increase it by using `perpage` query parameter up to 50. To get more also specify `page` query parameter and make recursive requests until you get all items.

**Comment by starchildluke** [comment]
Thank you for your help and the quick response!
